eventsourcing/es4j

eventsourcing-core/src/main/java/com/eventsourcing/ClassEntitySubscriber.java, eventsourcing-core/src/main/java/com/eventsourcing/CommandConsumer.java, eventsourcing-core/src/main/java/com/eventsourcing/DispatchingCommandConsumer.java, eventsourcing-core/src/main/java/com/eventsourcing/DisruptorCommandConsumer.java, eventsourcing-core/src/main/java/com/eventsourcing/EntitySubscriber.java, eventsourcing-core/src/main/java/com/eventsourcing/Repository.java, eventsourcing-core/src/main/java/com/eventsourcing/RepositoryImpl.java, eventsourcing-core/src/test/java/com/eventsourcing/RepositoryTest.java, eventsourcing-h2/src/main/java/com/eventsourcing/h2/MVStoreJournal.java
In event sourcing, there are many cases when events/commands
need to be listened upon their serialization to ensure proactive
processing (aggregate root listeners, etc.), as opposed to lazy
index-based processing at a later point in time.
Solution: introduce EntitySubscriber interface that will receive
entities once they are committed.
=> Problem: impossible to listen for committed entities

eventsourcing-core/src/main/java/com/eventsourcing/DisruptorCommandConsumer.java, eventsourcing-core/src/main/java/com/eventsourcing/EntityHandle.java, eventsourcing-core/src/main/java/com/eventsourcing/JournalEntityHandle.java, eventsourcing-core/src/main/java/com/eventsourcing/MemoryJournal.java, eventsourcing-core/src/main/java/com/eventsourcing/index/SimpleAttribute.java, eventsourcing-core/src/test/java/com/eventsourcing/index/IndexEngineTest.java, eventsourcing-h2/src/main/java/com/eventsourcing/h2/MVStoreJournal.java
Its public interface exposed an implementation detail of using
Journals for accessing entities.
Solution: extract an interface and move existing implementation
to JournalEntityHandler
=> Problem: EntityHandle leaked implementation details

eventsourcing-core/build.gradle
=> Problem: cqengine 2.5.0 has been superseded

eventsourcing-h2/build.gradle, eventsourcing-h2/src/main/java/com/eventsourcing/h2/ByteBufferDataType.java, eventsourcing-h2/src/main/java/com/eventsourcing/h2/MVStoreJournal.java, eventsourcing-h2/src/test/java/com/eventsourcing/h2/ByteBufferDataTypeTest.java
Solution: implement numerous optimizations.
1. Reduce the amount of ByteBuffer allocations
2. Implement ByteBuffer MVStore serialization
3. Use transactional map's tryPut() instead of put()
as it doesn't read the original value
=> Problem: slow MVStoreJournal

eventsourcing-h2/build.gradle
Solution: upgrade to 1.4.192
This release has improvements to MVStore
=> Problem: h2 1.4.191 was superseded

eventsourcing-layout/src/main/java/com/eventsourcing/layout/types/UnknownTypeHandler.java
Solution: include it in the fingerprint
=> Problem: Unknown type handler fingerprint loses type information

eventsourcing-hlc/src/main/java/com/eventsourcing/hlc/HybridTimestamp.java, eventsourcing-hlc/src/test/java/com/eventsourcing/hlc/HybridTimestampTest.java
Solution: remove byte array property and follow 6/HLC
Depends on merging https://github.com/eventsourcing/rfc/pull/38
=> Problem: HybridTimestamp doesn't follow the layout defined in 6/HLC

eventsourcing-core/src/main/java/com/eventsourcing/index/CascadingIndexEngine.java
Solution: fix the service.pid exclusion reference
=> Problem: In OSGi, CascadingIndexEngine self-references, creating a loop

eventsourcing-core/src/main/java/com/eventsourcing/CommandConsumer.java, eventsourcing-core/src/main/java/com/eventsourcing/DispatchingCommandConsumer.java, eventsourcing-core/src/main/java/com/eventsourcing/DisruptorCommandConsumer.java, eventsourcing-core/src/main/java/com/eventsourcing/Repository.java, eventsourcing-core/src/main/java/com/eventsourcing/RepositoryImpl.java, eventsourcing-core/src/test/java/com/eventsourcing/RepositoryTest.java
This is useful both for disconnected systems and testing
Solution: only timestamp a command if it doesn't have a timestamp already
=> Problem: command's timestamp can't be specified before publishing

eventsourcing-core/src/main/java/com/eventsourcing/DisruptorCommandConsumer.java, eventsourcing-core/src/main/java/com/eventsourcing/MemoryJournal.java, eventsourcing-core/src/test/java/com/eventsourcing/RepositoryTest.java, eventsourcing-h2/src/main/java/com/eventsourcing/h2/MVStoreJournal.java
This is useful for testing and disconnected systems
Solution: similarly to commands, event's timestamp will be overriden
only if it doesn't have one.
Also, this changes the behaviour of the repository. Before, the timestamp
of the repository was the timestamp of the last command. Now, it's the
timestamp of the last command's last event.
=> Problem: impossible to timestamp events before publishing a command

eventsourcing-core/src/main/java/com/eventsourcing/index/Indexing.java, eventsourcing-core/src/test/java/com/eventsourcing/index/IndexingTest.java
This is a bad behaviour because it obscures the problem and it can't be found easily.
Solution: throw an exception when the property was not found
=> Problem: Indexing.getAttribute silently fails if the property was not found

eventsourcing-core/src/main/java/com/eventsourcing/index/IndexEngine.java, eventsourcing-core/src/main/java/com/eventsourcing/index/Indexing.java, eventsourcing-core/src/test/java/com/eventsourcing/index/IndexEngineTest.java
This results in an exception thrown (as the same static variable that uses Indexing.getAttribute is being
analyzed).
Solution: Indexing.getAttributes should only scan for getter-based indices
=> Problem: Indexing.getAttribute results in recursive traversal of the same class

eventsourcing-core/src/main/java/com/eventsourcing/Repository.java
Frequent time sync fetches an IP ban
Solution: revert to localhost by default
=> Problem: Repository.create() uses global NTP servers by default

eventsourcing-hlc/src/main/java/com/eventsourcing/hlc/NTPServerTimeProvider.java
Frequest restarts cause service disruption and are against ntp.pool.org
[Terms of Service](http://www.pool.ntp.org/tos.html):
4.	End-User agrees that he or she will not:
(a)	Change default settings to make more frequent request of the Services, if using an ntp daemon (“NTP Protocol”);
Solution: use localhost as the first choice
=> Problem: by default, NTPServerTimeProvider goes to ntp.pool.org

eventsourcing-layout/src/main/java/com/eventsourcing/layout/types/ByteArrayTypeHandler.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/types/PrimitiveTypeHandler.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java, eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLJournalTest.java
PostgreSQL storage does not use eventsourcing-layout to serialize
values (because it maps them to PostgreSQL types)
Solution: write separate serialization tests for PostgreSQL
=> Problem: PostgreSQL serialization is untested

.gitignore, build.gradle, eventsourcing-core/src/main/java/com/eventsourcing/repository/EntitySubscriber.java
Not only javadoc will fail to recognize some constructs Lombok code is using,
but more importantly, it will fail to see auto-generated code
Solution: delombok code before running javadoc on it
=> Problem: running javadoc on pre-lombok sources is error-prone

eventsourcing-h2/src/main/java/com/eventsourcing/h2/MVStoreJournal.java
When journalling CommandTerminatedExceptionally raises an exception, MVStoreJournal
goes into an inifite recursion trying to report that with another CommandTerminatedExceptionally
Solution: throw an exception if it is generated during CommandTerminatedExceptionally journalling
=> Problem: MVStoreJournal#journal goes into an infinite recursion

docs/core_concepts/layout.md, eventsourcing-core/src/main/java/com/eventsourcing/StandardCommand.java, eventsourcing-core/src/main/java/com/eventsourcing/StandardEntity.java, eventsourcing-core/src/main/java/com/eventsourcing/StandardEvent.java, eventsourcing-core/src/main/java/com/eventsourcing/repository/DisruptorCommandConsumer.java, eventsourcing-core/src/test/java/com/eventsourcing/RepositoryTest.java, eventsourcing-core/src/test/java/com/eventsourcing/StandardCommandTest.java, eventsourcing-core/src/test/java/com/eventsourcing/StandardEntityTest.java, eventsourcing-core/src/test/java/com/eventsourcing/StandardEventTest.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/Layout.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/binary/ObjectBinaryDeserializer.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/binary/ObjectBinarySerializer.java, eventsourcing-layout/src/test/java/com/eventsourcing/layout/LayoutTest.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/AddProductToOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/AdjustItemQuantity.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/CancelOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/ChangePrice.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/CreateOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/CreateProduct.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/RemoveItemFromOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/Rename.java, examples/order/src/main/java/com/eventsourcing/examples/order/events/ItemQuantityAdjusted.java, examples/order/src/main/java/com/eventsourcing/examples/order/events/ItemRemovedFromOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/events/NameChanged.java, examples/order/src/main/java/com/eventsourcing/examples/order/events/OrderCancelled.java, examples/order/src/main/java/com/eventsourcing/examples/order/events/OrderCreated.java, examples/order/src/main/java/com/eventsourcing/examples/order/events/PriceChanged.java, examples/order/src/main/java/com/eventsourcing/examples/order/events/ProductAddedToOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/events/ProductCreated.java
Having to create a matching construtor for any kind of entity is
good when explicitness is sought. However, it's definitely adding
some verbosity:
```java
@Builder
public MyEvent(HybridTimestamp timestamp, String value) {
super(timestamp);
this.value = value
}
```
Solution: make layout detect inherited properties
These properties MUST also have setters in order to be successfully
initialized upon instantiation.
Now the inherited properties can be omitted (but if explicitness is
required, they can be declared in the constructor explictly as well)
This merge also adds `Layout#instantiate()` method.
=> Problem: having to pass timestamp to all entities is a nuisance

eventsourcing-kotlin/build.gradle, eventsourcing-kotlin/src/main/kotlin/Layout.kt, eventsourcing-kotlin/src/test/kotlin/LayoutTest.kt, eventsourcing-layout/src/main/java/com/eventsourcing/layout/ClassAnalyzer.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/JavaClassAnalyzer.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/Layout.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/UseClassAnalyzer.java, settings.gradle
See http://stackoverflow.com/questions/30425846/how-to-get-parameter-names-via-reflection-in-kotlin
This forces Kotlin users to use @PropertyName for every parameter, which
is a suboptimal user experience.
Solution: Add @UseClassAnalyzer annotation that allows to specify
a custom class analyzer that will return propert parameter names.
This solution also implements KotlinClassAnalyzer.
=> Problem: Kotlin doesn't produce parameter names readable by Java 8

eventsourcing-core/src/main/java/com/eventsourcing/repository/RepositoryImpl.java
This causes other services that depend on a fully running repository to fail
Solution: wait until the repository has been properly started
=> Problem: OSGi StandardRepository#activate() doesn't wait until started

eventsourcing-layout/src/test/java/com/eventsourcing/layout/LayoutTest.java
This means that there is no such guarantee at the moment.
Solution: implement such a test
=> Problem: no test ensures Layout picks the widest constructor

build.gradle
This increases the length of repeated builds significantly
Solution: Set inputs and outputs to relevant tasks to prevent the re-runs
=> Problem: Gradle re-runs delombok and javadocs when nothing has changed

eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLSerialization.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/EqualityIndex.java
Should the way postgresql storage organizes tables change, it'll be
a little bit of nuisance to figure out if the upgrade is necessary.
Solution: include "adapter schema" version in the identifiers of
tables and types
=> Problem: postgresql storage tables are hard to migrate to new versions

eventsourcing-core/src/main/java/com/eventsourcing/index/AbstractAttributeIndex.java, eventsourcing-core/src/main/java/com/eventsourcing/index/CQIndexEngine.java, eventsourcing-core/src/main/java/com/eventsourcing/index/MemoryIndexEngine.java, eventsourcing-core/src/test/java/com/eventsourcing/index/EqualityIndexTest.java, eventsourcing-core/src/test/java/com/eventsourcing/index/MemoryHashIndexTest.java, eventsourcing-h2/src/main/java/com/eventsourcing/h2/index/UniqueIndex.java, eventsourcing-migrations/src/main/java/com/eventsourcing/migrations/LayoutMigration.java, eventsourcing-migrations/src/main/java/com/eventsourcing/migrations/events/EntityLayoutIntroduced.java, eventsourcing-repository/src/main/java/com/eventsourcing/repository/commands/IntroduceEntityLayouts.java
This prevents us from using byte[] in indices, especially such
core indices as EntityLayoutIntroduced.fingerprint.
Solution: handle byte[] as a special case
Also, change EntityLayoutIntroduced.fingerprint attribute
to byte[]
=> Problem: byte[] equality does not work in MemoryIndexEngine

eventsourcing-core/src/main/java/com/eventsourcing/Command.java, eventsourcing-core/src/main/java/com/eventsourcing/events/CommandTerminatedExceptionally.java, eventsourcing-core/src/main/java/com/eventsourcing/events/JavaExceptionOccurred.java, eventsourcing-repository/build.gradle, eventsourcing-repository/src/main/java/com/eventsourcing/repository/AbstractJournal.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java
Solution: Make it adhere to RFC 9/RIG
Introduces following API improvements:
1. Adds `JavaExceptionOccurred` exception
2. Adds `Command#hasTerminatedExceptionally` method
3. Adds `Command#exceptionalTerminationCause` method
Closes #85
=> Problem: CommandTerminatedExceptionally does not follow RFC 9/RIG layout

eventsourcing-core/src/test/java/com/eventsourcing/index/MemoryNavigableIndexTest.java
Solution: annotate MemoryNavigableIndexTest with `@Test` to include it
=> Problem: MemoryNavigableIndexTest not included into `gradle check` test plan

eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/Deleted.java, eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/DescriptionChanged.java, eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/NameChanged.java, eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/Undeleted.java, eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DeletedProtocolTest.java, eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DescriptionProtocolTest.java, eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/NameProtocolTest.java
This requirement was imposed when Layout did not support
inherited properties.
Solution: expose constructors with events' own properties
=> Problem: CEP events constructors require a timestamp

docs/core_concepts/command.md, docs/core_concepts/event.md, docs/core_concepts/repository.md
This is no longer necessary.
Solution: update the documentation to use more succinct definitions
=> Problem: documentation uses explicit entity constructors

docs/core_concepts/command.md
=> Problem: Documentation on Command lists type parameters in a wrong order

eventsourcing-hlc/src/main/java/com/eventsourcing/hlc/HybridTimestamp.java, eventsourcing-hlc/src/test/java/com/eventsourcing/hlc/HybridTimestampTest.java, eventsourcing-repository/src/main/java/com/eventsourcing/repository/CommandConsumerImpl.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java
Solution: fix a bug in HybridTimestamp
Updating a HybridTimestamp with another HybridTimestamp mistakenly re-processed
logical time and counter and sent the clocks off the future upon initial timestamp
updates with initial commands.
=> Problem: starting repository clocks are off in the future

eventsourcing-core/src/test/java/com/eventsourcing/index/EqualityIndexTest.java, eventsourcing-core/src/test/java/com/eventsourcing/index/NavigableIndexTest.java, eventsourcing-core/src/test/java/com/eventsourcing/index/UniqueIndexTest.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/EqualityIndex.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/NavigableIndex.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/PostgreSQLAttributeIndex.java
For example, `EqualityIndex` will re-add existing data, and `EqualityIndex`
with `unique` set will throw an exception.
Solution: establish row uniqueness guarantees and use PostgreSQL 9.5
ON CONFLICT DO NOTHING feature when appropriate
=> Problem: PostgreSQL indices reinitialization breaks data constraints

eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DeletedProtocol.java, eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DescriptionProtocol.java, eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/NameProtocol.java, eventsourcing-core/src/main/java/com/eventsourcing/Protocol.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/LatestAssociatedEntryQuery.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/ModelQueries.java
Not only this is error-prone, it also adds a considerable amount of noise.
Solution: Extract com.eventsourcing.queries.ModelQueries interface that
provides this functionality by including LatestAssociatedEntryQuery
interface, which implements the `#latestAssociatedEntity` method.
=> Problem: repeating the snippet for retrieving last entity is a nuisance

eventsourcing-core/src/main/java/com/eventsourcing/index/EntityQueryFactory.java, eventsourcing-queries/src/main/java/com/eventsourcing/queries/IsLatestEntity.java, eventsourcing-queries/src/main/java/com/eventsourcing/queries/ModelQueries.java, eventsourcing-queries/src/main/java/com/eventsourcing/queries/QueryFactory.java, eventsourcing-queries/src/test/java/com/eventsourcing/queries/IsLatestEntityTest.java
The type of query would be "give me the latest instance of NameChanged of all
NameChanged related to a Person"
Solution: introduce a specialy IsLatestEntity query
Now it is possible to write something like this:
```java
Query<EntityHandle<NameChanged>> isPerson = existsIn(
repository.getIndexEngine().getIndexedCollection(PersonRegistered.class),
NameChanged.REFERENCE_ID, PersonRegistered.ID);
Query<EntityHandle<NameChanged>> latestEntity =
isLatestEntity(repository.getIndexEngine().getIndexedCollection(NameChanged.class),
(v) -> equal(NameChanged.REFERENCE_ID, v.get().reference()),
NameChanged.TIMESTAMP);
Query<EntityHandle<NameChanged>> query = and(latestEntity, isPerson);
```
Please note that it is quite slow so far. Hoping we can get a more efficient solution.
=> Problem: querying for latest entities across a broader condition is difficult

eventsourcing-core/src/main/java/com/eventsourcing/index/AbstractAttribute.java, eventsourcing-core/src/main/java/com/eventsourcing/index/MultiValueAttribute.java, eventsourcing-core/src/main/java/com/eventsourcing/index/SimpleAttribute.java, eventsourcing-queries/src/main/java/com/eventsourcing/queries/IsLatestEntity.java
`IllegalStateException: An equivalent index has already been added for attribute`
Solution: override equality testing and hashCode in Eventsourcing's
SimpleAttribute and MultiValueAttribute.
The problem was that the `objectType` passed to cqengine was always
`EntityHandle` which obviously has the same hash code for any entity.
By overriding these and checking the effective object type, cqengine
no longer thinks this index has already been added.
=> Problem: cqengine refuses to add more indices

eventsourcing-queries/src/main/java/com/eventsourcing/queries/ModelCollectionQuery.java, eventsourcing-queries/src/test/java/com/eventsourcing/queries/ModelCollectionQueryTest.java
Having one-off model collection query methods is good for simple
applications, but when combinations of those queries are required,
compisability is often sought.
Solution: introduce ModelCollectionQuery interface to compose
the queries.
=> Problem: composing model collection queries is difficult

eventsourcing-core/src/main/java/com/eventsourcing/ResolvedEntityHandle.java, eventsourcing-core/src/test/java/com/eventsourcing/index/NavigableIndexTest.java, eventsourcing-core/src/test/java/com/eventsourcing/index/UniqueIndexTest.java, eventsourcing-core/src/test/java/com/eventsourcing/models/CarFactory.java, eventsourcing-h2/src/main/java/com/eventsourcing/h2/index/HashIndex.java, eventsourcing-h2/src/main/java/com/eventsourcing/h2/index/UniqueIndex.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/PostgreSQLAttributeIndex.java, src/jmh/java/com/eventsourcing/jmh/HashIndexBenchmark.java
It doesn't use any repository-related concepts (unlike JournalEntityHandle,
for example)
Solution: Move it to eventsourcing-core
=> Problem: ResolvedEntityHandle does not belong to eventsourcing-repository

eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DeletedProtocolTest.java, eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DescriptionProtocolTest.java, eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/NameProtocolTest.java, eventsourcing-core/src/main/java/com/eventsourcing/StandardCommand.java, eventsourcing-core/src/test/java/com/eventsourcing/StandardCommandTest.java, eventsourcing-core/src/test/java/com/eventsourcing/index/IndexEngineTest.java, eventsourcing-migrations/src/test/java/com/eventsourcing/migrations/LayoutMigrationTest.java, eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLJournalTest.java, eventsourcing-queries/src/test/java/com/eventsourcing/queries/IsLatestEntityTest.java, eventsourcing-queries/src/test/java/com/eventsourcing/queries/ModelQueriesTest.java, eventsourcing-repository/src/main/java/boguspackage/BogusCommand.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/JournalTest.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/AddProductToOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/AdjustItemQuantity.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/CancelOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/ChangePrice.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/CreateOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/CreateProduct.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/RemoveItemFromOrder.java, examples/order/src/main/java/com/eventsourcing/examples/order/commands/Rename.java, src/jmh/java/com/eventsourcing/jmh/TestCommand.java
Often times, the repository is not needed to produce events
Solution: provide a no-arguments method that would be called if
no other methods are overriden.
=> Problem: having to declare Repository arg in StandardCommands#events

.travis.yml, build.gradle
When new module is added, it is sometimes hard to remember to add it
to all the necessary places in the build system
Solution: simply rely on Gradle's knowledge of subprojects.
=> Problem: maintaining an explicit list of modules to upload to bintray

eventsourcing-layout/src/main/java/com/eventsourcing/layout/Layout.java, eventsourcing-layout/src/test/java/com/eventsourcing/layout/LayoutTest.java
Solution: treat null values as if they weren't defined, allowing
to use the default type values.
=> Problem: exception when null values are passed in Layout#instantiate

eventsourcing-repository/src/main/java/com/eventsourcing/repository/StandardRepository.java
The problem occurs in OSGi environments when IndexEngine can (supposedly)
get re-wired to a new StandardRepository instance. If IndexEngine has the
index added, when StandardRepository is wired to events/commands again,
it will attempt to add those indices again.
Related issue: https://github.com/npgall/cqengine/issues/79
Solution: check if it was an attempt to add an equivalent index, and if it was,
swallow the exception.
This is not a perfect solution, but if https://github.com/npgall/cqengine/issues/79 gets
solved, it can be improved.
=> Problem: failure to start StandardRepository with duplicate indices

docs/getting_started/publishing.md, eventsourcing-queries/src/test/java/com/eventsourcing/queries/RepositoryUsingTest.java, eventsourcing-repository/src/main/java/com/eventsourcing/repository/StandardRepository.java
Solution: implement StandardRepository.builder() to prettify
its initialization.
=> Problem: StandardRepository initialization doesn't look pretty

eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/Deleted.java, eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/DescriptionChanged.java, eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/NameChanged.java, eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/Undeleted.java, eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DeletedProtocolTest.java, eventsourcing-core/src/main/java/com/eventsourcing/events/CommandTerminatedExceptionally.java, eventsourcing-core/src/main/java/com/eventsourcing/events/EventCausalityEstablished.java, eventsourcing-core/src/main/java/com/eventsourcing/events/JavaExceptionOccurred.java, eventsourcing-core/src/main/java/com/eventsourcing/index/IndexEngine.java, eventsourcing-core/src/main/java/com/eventsourcing/index/MultiValueIndex.java, eventsourcing-core/src/main/java/com/eventsourcing/index/SimpleIndex.java, eventsourcing-core/src/test/java/com/eventsourcing/index/IndexEngineTest.java, eventsourcing-kotlin/src/test/kotlin/EntityTest.kt, eventsourcing-migrations/src/main/java/com/eventsourcing/migrations/events/EntityLayoutIntroduced.java, eventsourcing-migrations/src/main/java/com/eventsourcing/migrations/events/EntityLayoutReplaced.java, eventsourcing-queries/src/test/java/com/eventsourcing/queries/IsLatestEntityTest.java, eventsourcing-queries/src/test/java/com/eventsourcing/queries/ModelQueriesTest.java, eventsourcing-repository/src/main/java/boguspackage/BogusEvent.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java, examples/foodsourcing/src/main/java/foodsourcing/events/AddressChanged.java, examples/foodsourcing/src/main/java/foodsourcing/events/MenuItemAdded.java, examples/foodsourcing/src/main/java/foodsourcing/events/PictureChanged.java, examples/foodsourcing/src/main/java/foodsourcing/events/PriceChanged.java, examples/foodsourcing/src/main/java/foodsourcing/events/RestaurantRegistered.java, examples/foodsourcing/src/main/java/foodsourcing/events/WorkingHoursChanged.java
Most of the time, for most of use cases, there is no need for indices to be
aware of query options.
Also, having a two-arguments lambda prevents us from using
method references (which is a very common scenario when we need
to index a property as is)
Solution: make a one-argument functional interface a default
syntax in SimpleIndex and MultiValueIndex and add a #withQueryOptions
static helper to allow two-arguments functions to be supplied
to access query options.
=> Problem: index definition syntax is slightly verbose

eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLSerialization.java
This only happens when deserializing arrays
Solution: enclose this ResultSet in a try-with-resources
=> Problem: PostgreSQL deserializer leaks ResultSets

eventsourcing-core/src/main/java/com/eventsourcing/index/IndexEngine.java, eventsourcing-core/src/main/java/com/eventsourcing/index/IndexLoader.java, eventsourcing-core/src/main/java/com/eventsourcing/index/JavaStaticFieldIndexLoader.java, eventsourcing-kotlin/src/test/kotlin/EntityTest.kt, eventsourcing-repository/src/main/java/com/eventsourcing/repository/StandardRepository.java
It couples the discovery with definition and is not well suited for providing
different mechanisms to load indices, particularly other JVM languages.
Solution: extract an IndexLoader interface and move current implementation to
JavaStaticFieldIndexLoader.
=> Problem: index discovery mechanism is hard-coded

eventsourcing-postgresql/build.gradle
In pgjdbc-ng, Import-Package is defined as:
```
io.netty.*;version="[4.0,4.1)",
```
However, netty-all's MANIFEST.MF does not contain any OSGi
information:
```
Manifest-Version: 1.0
Implementation-Vendor: The Netty Project
Implementation-Title: Netty/All-in-One
Implementation-Version: 4.0.40.Final
Implementation-Vendor-Id: io.netty
Built-By: norman
Build-Jdk: 1.7.0_85
Created-By: Apache Maven 3.3.3
Implementation-URL: http://netty.io/netty-all/
```
When installed, it exports packages without version information:
```
eid@eid> install -s wrap:mvn:io.netty/netty-all/4.0.40.Final
Bundle ID: 61
eid@eid> headers 61
wrap_mvn_io.netty_netty-all_4.0.40.Final (61)
...
Export-Package =
io.netty.bootstrap;uses:="io.netty.channel,io.netty.util",
...
```
And therefore fails pgjdbc-ng's requirement:
``` …
```
=> Problem: netty-all doesn't work in OSGi environment

eventsourcing-core/src/main/java/com/eventsourcing/EntitySubscriber.java, eventsourcing-repository/src/main/java/com/eventsourcing/repository/CommandConsumerImpl.java
In OSGi, when using Declarative Services, this results in a loop because
StandardRepository references EntitySubscribers.
In non-OSGi environments, a reference to repository must be passed to the
subscriber.
Solution: augment EntitySubscriber API to allow (optional) capture of the
repository.
=> Problem: getting a repository in an entity subscriber is difficult

eventsourcing-core/src/main/java/com/eventsourcing/index/JavaStaticFieldIndexLoader.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java
In all index engines, besides MemoryIndexEngine, this is what
happens:
```
Caused by: java.lang.ClassCastException: sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl cannot be cast to java.lang.reflect.AnnotatedParameterizedType
at com.eventsourcing.index.AbstractAttributeIndex.<init>(AbstractAttributeIndex.java:48)
```
Solution: add superclass type arguments to JavaStaticFieldIndexLoader.MultiValueEntityAttribute
The reason why the above exception has occured was that AbstractAttributeIndex was trying to read
type information and failing to do so, as it wasn't specified.
=> Problem: Use of MultiValueIndex results in an exception

eventsourcing-core/src/main/java/com/eventsourcing/index/AbstractAttributeIndex.java, eventsourcing-core/src/main/java/com/eventsourcing/index/JavaStaticFieldIndexLoader.java, eventsourcing-core/src/main/java/com/eventsourcing/index/MultiValueAttribute.java, eventsourcing-core/src/main/java/com/eventsourcing/index/ReflectableAttribute.java, eventsourcing-core/src/main/java/com/eventsourcing/index/SimpleAttribute.java, eventsourcing-core/src/test/java/com/eventsourcing/index/AbstractAttributeIndexTest.java, eventsourcing-h2/src/main/java/com/eventsourcing/h2/index/HashIndex.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/Layout.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/TypeHandler.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/types/ListTypeHandler.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/types/MapTypeHandler.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/types/OptionalTypeHandler.java, eventsourcing-layout/src/test/java/com/eventsourcing/layout/types/EnumTypeHandlerTest.java, eventsourcing-layout/src/test/java/com/eventsourcing/layout/types/ListTypeHandlerTest.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLSerialization.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/EqualityIndex.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/NavigableIndex.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java
For example, an attribute of a List<String> will result in a runtime exception of
an invalid type cast.
Solution: simplify type handler resolution and ensure typing information gets
through correctly.
Also, address an issue discovered in pgjdbc-ng
(https://github.com/impossibl/pgjdbc-ng/issues/288), to be reviewed again
later.
Also, fix discovered serializing issues in eventsourcing-h2 indexing.
=> Problem: impossible to index non-primitive attributes

eventsourcing-repository/src/main/java/com/eventsourcing/repository/CommandConsumerImpl.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java
If a command has terminated exceptionally, it doesn't make a whole lot of sense
to call its `#result()` as it, at best, it won't be consistent.
What makes it worse, we currently call it with a state of the new event stream
that encapsulates abnormal termination events which always has a `null` state
and that's what being passed to `#result()`.
Solution: don't call `Command#result()` if the command has terminated
exceptionally.
=> Problem: exceptionally terminated commands' result() is called

eventsourcing-core/src/main/java/com/eventsourcing/index/Indices.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java
Kudos to @bsrk for reporting this
Solution: retain `@Indices` in runtime to be able to detect it
=> Problem: `@Indices` annotation has no effect

eventsourcing-core/src/main/java/com/eventsourcing/EntitySubscriber.java
Specifically, if one doesn't need a repository, and overrides EntitySubscriber#accept(Stream),
when command is processed, EntitySubscriber#accept(Repository, Stream) is invoked
which is set up to call #onEntity(Repository, entity) on all entities, entirely bypassing
EntitySubscriber#accept(Stream).
Solution: deprecate EntitySubscriber#accept(Stream)
=> Problem: EntitySubscriber#accept(Stream) leads to confusing bugs

eventsourcing-cep/build.gradle, eventsourcing-core/build.gradle, eventsourcing-inmem/build.gradle, eventsourcing-migrations/build.gradle, eventsourcing-queries/build.gradle, eventsourcing-repository/build.gradle, eventsourcing-repository/src/main/java/com/eventsourcing/repository/QuerySubscriber.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/QuerySubscriberTest.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryUsingTest.java
Once a query is executed, it is impossible to know when the data queried
against has changed, leaving us to requery
at some time intervals.
Solution: implement a QuerySubscriber that would listen to all entities and
notify its own subscribers that a particular
query's set has changed.
It is rather simplistic for now, and I am not quite sure it is suitable for all scenarios,
but we can address this later, and if it doesn't work out, remove it. One of the areas
for improvement is to implement query-and-subscribe.
=> Problem: it is impossible to know when query results change

eventsourcing-core/src/main/java/com/eventsourcing/index/CascadingIndexEngine.java, eventsourcing-postgresql/build.gradle, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/DataSourceProvider.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PooledDataSource.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLIndexEngine.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java, eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLRepositoryTest.java, eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLTest.java, examples/foodsourcing/src/test/java/foodsourcing/TestWithRepository.java, src/jmh/java/com/eventsourcing/jmh/PostgreSQLJournalBenchmark.java, src/jmh/java/com/eventsourcing/jmh/PostgreSQLRepositoryBenchmark.java
It's just too slow because it'll keep re-opening connections and re-scanning
types.
Solution: enforce pgjdbc-ng and make use of HikariCP underneath
Fixes #184
=> Problem: using postgresql backend without a pool is nearly impossible

eventsourcing-layout/src/main/java/com/eventsourcing/layout/TypeHandler.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/binary/BigIntegerBinaryDeserializer.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/binary/BigIntegerBinarySerializer.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/binary/BinarySerialization.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/comparable/BigIntegerComparableSerializer.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/comparable/ComparableSerialization.java, eventsourcing-layout/src/main/java/com/eventsourcing/layout/types/BigIntegerTypeHandler.java, eventsourcing-layout/src/test/java/com/eventsourcing/layout/SerializerTest.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLSerialization.java, eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLJournalTest.java
While it can be easily wrapped into BigDecimal, this creates an unnecessary
friction point.
Solution: provide support for BigInteger
=> Problem: layout does not support BigInteger

eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/RepositoryUsingTest.java, eventsourcing-core/src/test/java/com/eventsourcing/index/CascadingIndexEngineTest.java, eventsourcing-core/src/test/java/com/eventsourcing/index/EntityQueryFactoryTest.java, eventsourcing-h2/build.gradle, eventsourcing-h2/src/test/java/com/eventsourcing/h2/MVStoreJournalRepositoryTest.java, eventsourcing-inmem/build.gradle, eventsourcing-inmem/src/main/java/com/eventsourcing/inmem/MemoryIndexEngine.java, eventsourcing-inmem/src/test/java/com/eventsourcing/inmem/MemoryHashIndexTest.java, eventsourcing-inmem/src/test/java/com/eventsourcing/inmem/MemoryIndexEngineTest.java, eventsourcing-inmem/src/test/java/com/eventsourcing/inmem/MemoryNavigableIndexTest.java, eventsourcing-inmem/src/test/java/com/eventsourcing/inmem/MemoryUniqueIndexTest.java, eventsourcing-kotlin/build.gradle, eventsourcing-kotlin/src/test/kotlin/EntityTest.kt, eventsourcing-migrations/src/test/java/com/eventsourcing/migrations/RepositoryTest.java, eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLRepositoryTest.java, eventsourcing-queries/src/test/java/com/eventsourcing/queries/RepositoryUsingTest.java, eventsourcing-repository/src/main/java/com/eventsourcing/repository/QuerySubscriber.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/JournalTest.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java, eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryUsingTest.java, examples/foodsourcing/src/test/java/foodsourcing/TestWithRepository.java, src/jmh/java/com/eventsourcing/jmh/JournalBenchmark.java, src/jmh/java/com/eventsourcing/jmh/MemoryRepositoryBenchmark.java, src/jmh/java/com/eventsourcing/jmh/PostgreSQLRepositoryBenchmark.java
This violates the separation of backends in their own individual
modules.
Solution: move it to eventsourcing-inmem
=> Problem: MemoryIndexEngine is in eventsourcing-core

eventsourcing-core/src/main/java/com/eventsourcing/Journal.java, eventsourcing-core/src/main/java/com/eventsourcing/index/CommandJournalPersistence.java, eventsourcing-core/src/main/java/com/eventsourcing/index/EagerFetching.java, eventsourcing-core/src/main/java/com/eventsourcing/index/EventJournalPersistence.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/PostgreSQLAttributeIndex.java
Because of the way PostgreSQL journal event/command iteration works,
for every index re-addition entry in the batch, a separate query will
be executed to fetch the actual entity, which is incredibly slow.
Solution: introduce `EagerFetching` query option that instructs to
pre-fetch the entitites.
=> Problem: re-indexing upon index init causes N entity pgsql queries

eventsourcing-layout/src/main/java/com/eventsourcing/layout/Layout.java
It results in exceptions like: "com.foo.Barhas more than one constructor with 2
parameters and no @LayoutConstructor-annotated constructor"
Solution: add the missing space
=> Problem: a Layout-related exception is missing a space character

eventsourcing-hlc/build.gradle, eventsourcing-hlc/src/main/java/com/eventsourcing/hlc/HybridTimestamp.java, eventsourcing-hlc/src/test/java/com/eventsourcing/hlc/SerializableComparableTest.java
`getComparableSerializable().compareTo()` provably does not match the
results of `compareTo()` 100% of the time because it's converting the
timestamp to NTP, therefore reducing the precision.
Solution: switch from Long to BigInteger Comparable Serializable, pack
all data in a comparable order and test it with quickcheck.
=> Problem: HybridTimestamp Comparable Serializable isn't correct

eventsourcing-postgresql/build.gradle
It doesn't have a reference to PostgreSQL 9.6
Solution: upgrade postgresql-embedded to 1.19
=> Problem: postgresql-embedded is outdated

eventsourcing-core/src/test/java/com/eventsourcing/index/NavigableIndexTest.java, eventsourcing-core/src/test/java/com/eventsourcing/queries/MinMaxTest.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/NavigableIndex.java
```
Unsupported query: max("TIMESTAMP")
```
Solution: return an empty resultset if there are no items
in the collection
=> Problem: min/max queries (pgsql) fail on empty collections

eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/NavigableIndex.java, eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/index/PostgreSQLNavigableIndexTest.java
Previously, HybridTimestamp was serialized to long (BIGINT), it is
now serialized to BigInteger (NUMERIC). However, the version of the
index format wasn't incremented because format didn't change.
However, requiring everybody to manually drop indices with wrong
data type is not a great way to handle this case and this will surely
result in bug reports.
Solution: detect this case and drop "offending" indices automatically
=> Problem: a4d6711 changed HybridTimestamp navigable index key type

eventsourcing-core/src/main/java/com/eventsourcing/queries/IsLatestEntity.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/QueryFactory.java, eventsourcing-core/src/test/java/com/eventsourcing/queries/IsLatestEntityTest.java
min/max queries recently introduced a new way to pass the collection
via query options.
Solution: deprecate collection-taking isLatestEntity and introduce
new versions that get the implied collection instead.
=> Problem: isLatestEntity still requires to pass the collection

eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java
Solution: it appears that callback-based stopping mechanism doesn't
always work as expected — i.e. not notifying of termination. Callback
mechanism has been replaced with a simpler await-notify sequence.
=> Problem: in some cases, RepositoryTest.repositoryTimestamp() test hangs

eventsourcing-core/src/main/java/com/eventsourcing/OSGiEntitiesProvider.java
Since repository grabs the command / event set once, if new bundles are started
or existing ones are stopped, the changes in the command/event set can't be reflected.
Solution: make OSGiEntitiesProvider register per-bundle services when
the bundle is active.
=> Problem: OSGiEntitiesProvider's results are not updated over time

eventsourcing-core/src/main/java/com/eventsourcing/Repository.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/ComparingQuery.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/IsLatestEntity.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/Max.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/Min.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/QueryFactory.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/Scoped.java, eventsourcing-core/src/test/java/com/eventsourcing/index/NavigableIndexTest.java, eventsourcing-core/src/test/java/com/eventsourcing/queries/MinMaxTest.java, eventsourcing-core/src/test/java/com/eventsourcing/queries/ScopedTest.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/NavigableIndex.java, examples/foodsourcing/src/main/java/foodsourcing/Restaurant.java, examples/foodsourcing/src/test/java/foodsourcing/RestaurantTest.java
Min/Max queries are limited to finding the smallest or largest value of a
particular attribute globally across an entity. Which means you can tell
"what's the latest order" but not "what's the latest order for this person".
IsLatestEntity/LatestAssociatedEntryQuery are currently being used to address
this type of need, but they are very slow and cumbersome. Min/Max has been
already optimized for PostgreSQL storage.
Solution: introduce Scoped query to provide a different scope to a subquery:
```java
scoped(equal(Product.ID, id), max(Product.TIMESTAMP))
````
(It looks like even without backend-specific optimizations,
this query is a lot faster than `IsLatestEntity`)
Addresses #209
=> Problem: Min/Max queries are global to the attribute

eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLStatementIterator.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/PostgreSQLAttributeIndex.java
Problem: when fetching large datasets, pgsql driver runs out of memory
Solution: set fetch size at 10,000 rows
Problem: large additions to pgsql index run out of memory
Solution: manually form batches of up to 1000 records
=> Problem: Postgres backend runs out of memory

eventsourcing-core/src/main/java/com/eventsourcing/Journal.java, eventsourcing-core/src/main/java/com/eventsourcing/index/CommandJournalPersistence.java, eventsourcing-core/src/main/java/com/eventsourcing/index/EventJournalPersistence.java, eventsourcing-core/src/main/java/com/eventsourcing/index/JournalPersistence.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/options/EagerFetching.java, eventsourcing-core/src/main/java/com/eventsourcing/queries/options/NotSeenBy.java, eventsourcing-inmem/src/main/java/com/eventsourcing/inmem/MemoryJournal.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLStatementIterator.java, eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/PostgreSQLAttributeIndex.java
Upon index initialization, index has no idea if the object
store's data has been indexed.
Solution: in PostgreSQL-backed journal, assign sequential
IDs to entities and introduce the use of NotSeenBy query option
to avoid reindexing
=> Problem: reindexing large datasets is very time consuming
