eventsourcing/es4j

C4.md
CONTRIBUTING.md
README.md

Solution: Replace C4.1 with C4.2

Problem: C4.1 got obsoleted by C4.2

---

CONTRIBUTING.md
README.md

Solution: Replace with Unprotocols

Problem: C4 links still mention ZeroMQ

---

README.md

Solution: remove the notice, let the code itself and its
version number be an indicator

Problem: early version notice is discouraging

---

README.md

Solution: mention it in the README file

Problem: hard to find the presentation

---

eventsourcing-h2/src/main/java/com/eventsourcing/h2/ByteBufferDataType.java
eventsourcing-h2/src/test/java/com/eventsourcing/h2/ByteBufferDataTypeTest.java

Solution: read data from the ByteBuffer

Problem: ByteBufferDataType read is not suitable for reusable ByteBuffers

---

build.gradle

Problem: license headers were not correctly generated for benchmarks

---

src/jmh/java/com/eventsourcing/jmh/MVStoreJournalBenchmark.java

Problem: unnecessary output in a benchmark

---

docs/core_concepts/layout.md
eventsourcing-layout/src/main/java/com/eventsourcing/layout/TypeHandler.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/types/DateHandler.java
eventsourcing-layout/src/test/java/com/eventsourcing/layout/SerializerTest.java
examples/order/src/main/java/com/eventsourcing/examples/order/NameProtocol.java
examples/order/src/main/java/com/eventsourcing/examples/order/Order.java
examples/order/src/main/java/com/eventsourcing/examples/order/PriceProtocol.java
examples/order/src/main/java/com/eventsourcing/examples/order/Product.java
examples/order/src/main/java/com/eventsourcing/examples/order/QueryUtilities.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/AddProductToOrder.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/AdjustItemQuantity.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/CancelOrder.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/ChangePrice.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/CreateOrder.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/CreateProduct.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/RemoveItemFromOrder.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/Rename.java
examples/order/src/main/java/com/eventsourcing/examples/order/events/ItemQuantityAdjusted.java
examples/order/src/main/java/com/eventsourcing/examples/order/events/ItemRemovedFromOrder.java
examples/order/src/main/java/com/eventsourcing/examples/order/events/NameChanged.java
examples/order/src/main/java/com/eventsourcing/examples/order/events/OrderCancelled.java
examples/order/src/main/java/com/eventsourcing/examples/order/events/OrderCreated.java
examples/order/src/main/java/com/eventsourcing/examples/order/events/PriceChanged.java
examples/order/src/main/java/com/eventsourcing/examples/order/events/ProductAddedToOrder.java
examples/order/src/main/java/com/eventsourcing/examples/order/events/ProductCreated.java
examples/order/src/test/java/com/eventsourcing/examples/order/EventsourcingTest.java
examples/order/src/test/java/com/eventsourcing/examples/order/OrderTest.java
examples/order/src/test/java/com/eventsourcing/examples/order/ProductTest.java

Solution: implement DateHandler for java.util.Date
Closes #39

Problem: layout does not implement RFC1/ELF's Timestamp

---

MAINTAINERS.md

Solution: list current and former maintainers

Problem: hard to identify project maintainers

---

eventsourcing-core/src/main/java/com/eventsourcing/MemoryJournal.java

Solution: stop recording normal events in this situation

Problem: Memory Journal records normal events upon exceptional termination

---

eventsourcing-core/src/test/java/com/eventsourcing/index/IndexEngineTest.java

Solution: ensure command is timestamped and event can be deserialized

Problem: IndexEngine test failing

---

eventsourcing-core/src/main/java/com/eventsourcing/MemoryLockProvider.java
eventsourcing-core/src/test/java/com/eventsourcing/LockProviderTest.java
eventsourcing-core/src/test/java/com/eventsourcing/MemoryJournalRepositoryTest.java
eventsourcing-core/src/test/java/com/eventsourcing/MemoryJournalTest.java
eventsourcing-core/src/test/java/com/eventsourcing/MemoryLockProviderTest.java
eventsourcing-h2/src/test/java/com/eventsourcing/h2/MVStoreJournalRepositoryTest.java
eventsourcing-h2/src/test/java/com/eventsourcing/h2/MVStoreJournalTest.java

Solution: make all tests detectable by marking inheriting tests with no methods
with a @Test annotation

Problem: gradle test doesn't run all tests

---

build.gradle
eventsourcing-h2/build.gradle
examples/order/build.gradle

See https://github.com/h2database/h2database/pull/306
Solution: use an interim custom build of h2
Closes #48

Problem: org.h2.mvstore.db missing requirement in OSGi

---

eventsourcing-core/src/test/java/com/eventsourcing/JournalTest.java
eventsourcing-h2/src/main/java/com/eventsourcing/h2/MVStoreJournal.java

This is primarily caused by a previous wrongful memory allocation optimization.
Solution: Remove the memory allocation optimization and use higherKey as a starting
point for iterating

Problem: command hash keys overwriten in MVStoreJournal

---

docs/core_concepts/indexing.md
eventsourcing-core/build.gradle
eventsourcing-core/src/main/java/com/eventsourcing/annotations/Index.java
eventsourcing-core/src/main/java/com/eventsourcing/index/AbstractIndexEngine.java
eventsourcing-core/src/main/java/com/eventsourcing/index/Attribute.java
eventsourcing-core/src/main/java/com/eventsourcing/index/CascadingIndexEngine.java
eventsourcing-core/src/main/java/com/eventsourcing/index/IndexEngine.java
eventsourcing-core/src/main/java/com/eventsourcing/index/Indexing.java
eventsourcing-core/src/main/java/com/eventsourcing/index/SimpleAttribute.java
eventsourcing-core/src/test/java/com/eventsourcing/index/IndexEngineTest.java

Solution: allow specifying an index on a getter

Problem: simple index definition for properties is too noisy and complex

---

eventsourcing-layout/src/main/java/com/eventsourcing/layout/Layout.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/Property.java
eventsourcing-layout/src/test/java/com/eventsourcing/layout/LayoutTest.java
eventsourcing-layout/src/test/java/com/eventsourcing/layout/PropertyTest.java

Having them conform will simplify metainformation storage.
Solution: update them to conform to 7/LDL

Problem: Layout and Property do not fully conform to 7/LDL

---

README.md

Problem: no logo in README

---

eventsourcing-core/src/main/java/com/eventsourcing/Entity.java

Problem: Entity static initializer uses ForkJoinPool that might reuse current thread

---

eventsourcing-core/src/main/java/com/eventsourcing/index/Indexing.java

Problem: Indexing.getAttribute is StandardEntity-typed, constrains the hierarchy of classes

---

eventsourcing-core/src/main/java/com/eventsourcing/repository/LocalLockProvider.java

Problem: LocalLock is still being named MemoryLock in a few places

---

eventsourcing-core/src/main/java/com/eventsourcing/Repository.java
eventsourcing-core/src/main/java/com/eventsourcing/repository/RepositoryImpl.java

Solution: Add getter methods in Repository.

Problem: Kotlin needs getter methods in order to use property access.

---

eventsourcing-core/src/main/java/com/eventsourcing/repository/RepositoryImpl.java

Solution: rename timeProvider field to physicalTimeProvider
to be able to leverage Lombok's `@Getter`

Problem: non-minimal RepositoryImpl#getPhysicalTimeProvider getter 

---

build.gradle

Solution: Add proper tasks to the Gradle build script and configure Maven Publishing accordingly.

Problem: Source and Javadoc Jars are not published to Maven

---

.travis.yml
build.gradle
eventsourcing-core/src/test/java/com/eventsourcing/JournalTest.java
eventsourcing-postgresql/build.gradle
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/DataSourceProvider.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java
eventsourcing-postgresql/src/main/resources/com/eventsourcing/postgresql/migrations/V1_1__Create_Timestamp_Function.sql
eventsourcing-postgresql/src/main/resources/com/eventsourcing/postgresql/migrations/V1__Create_Layouts.sql
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLJournalTest.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgresSQLRepositoryTest.java
settings.gradle
src/jmh/java/com/eventsourcing/jmh/PostgreSQLJournalBenchmark.java
src/jmh/java/com/eventsourcing/jmh/PostgreSQLRepositoryBenchmark.java

Also, it grows quite large and doesn't have a lot of capabilities
for operations (backups, replication).
It also makes debugging and introspection harder
Solution: Add a PostgreSQLJournal
This implementation is naive and likely quite suboptimal,
but it might be useful

Problem: MVStoreJournal is stil somewhat buggy

---

eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DeletedProtocolTest.java
eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DescriptionProtocolTest.java
eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/NameProtocolTest.java
eventsourcing-core/src/main/java/com/eventsourcing/StandardCommand.java
eventsourcing-core/src/test/java/boguspackage/BogusCommand.java
eventsourcing-core/src/test/java/com/eventsourcing/RepositoryTest.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLJournalTest.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/AddProductToOrder.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/ChangePrice.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/CreateOrder.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/CreateProduct.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/Rename.java
src/jmh/java/com/eventsourcing/jmh/TestCommand.java

Solution: flip the type parameters

Problem: StandardCommand type parameters order does not match Command

---

eventsourcing-core/src/main/java/com/eventsourcing/repository/AbstractJournal.java
eventsourcing-core/src/main/java/com/eventsourcing/repository/Journal.java
eventsourcing-h2/src/main/java/com/eventsourcing/h2/MVStoreJournal.java
eventsourcing-inmem/src/main/java/com/eventsourcing/inmem/MemoryJournal.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java

There is a risk for introducing slightly incompatible behaviours,
and its just generally harder to maintain different journal implementations.
Solution: implement AbstractJournal

Problem: Different journal implementations share a lot

---

eventsourcing-kotlin/src/main/kotlin/Layout.kt
eventsourcing-layout/src/main/java/com/eventsourcing/layout/ClassAnalyzer.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/JavaClassAnalyzer.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/Layout.java

Solution: Redesign layout's ClassAnalyzer interface to
allow for the passage of typing information

Problem: Kotlin compiler reports an unchecked cast

---

eventsourcing-repository/src/main/java/com/eventsourcing/repository/CommandConsumerImpl.java
eventsourcing-repository/src/main/java/com/eventsourcing/repository/StandardRepository.java

Solution: Rename it to CommandConsumerImpl
Also, perform a very minor cleanup of CommandConsumerImpl

Problem: DisruptorCommandConsumer class name is confusing

---

eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLLockProvider.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLLockProviderTest.java

LocalLockProvider will not lock out other nodes.
Solution: implement PostgreSQLLockProvider

Problem: no shared locks for multi-node deployments

---

eventsourcing-core/src/test/java/com/eventsourcing/index/NavigableIndexTest.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLIndexEngine.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/EqualityIndex.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/NavigableIndex.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/PostgreSQLAttributeIndex.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/index/PostgreSQLNavigableIndexTest.java

Solution: implement PostgreSQL NavigableIndex
It also moves a lot of common functionality to abstract PostgreSQLAttributeIndex

Problem: No less/greaterThan/between index for PostgreSQL

---

eventsourcing-h2/src/main/java/com/eventsourcing/h2/MVStoreJournal.java
eventsourcing-h2/src/test/java/com/eventsourcing/h2/PersistentMVStoreJournalTest.java

Solution: Make sure the payload ByteBuffer is a unique instance,
since we'll be reading it again for cloning the entity.
Also, remnants of the pre- 8/EMT layout information storage system
were removed.

Problem: PersistentMVStoreJournalTest.persistence test failing

---

eventsourcing-core/src/main/java/com/eventsourcing/index/MultiValueAttribute.java
eventsourcing-core/src/test/java/com/eventsourcing/index/NavigableIndexTest.java
eventsourcing-core/src/test/java/com/eventsourcing/models/Car.java
eventsourcing-hlc/src/main/java/com/eventsourcing/hlc/HybridTimestamp.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/SerializableComparable.java
eventsourcing-layout/src/test/java/com/eventsourcing/layout/SerializableComparableTest.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/NavigableIndex.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/PostgreSQLAttributeIndex.java

Solution: introduce SerializableComparable interface to indicate how classes
implementing it should be serialized for comparison.
HybridTimestamp now implements it.
Closes #105

Problem: postgresql navigable index over a timestamp has a composite key

---

.gitignore
book.js
docs/getting_started/install.md
gradle.properties

Solution: fetch the latest snapshot version using a gitbook plugin

Problem: current documentation shows an outdated version in installation

---

build.gradle

Solution: throw an exception if git version is somehow coming up as `unspecified`

Problem: somehow, version `unspecified` was uploaded to maven-snapshots

---

docs/core_concepts/domain_model.md
docs/core_concepts/domain_protocol.md
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DeletedProtocol.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DescriptionProtocol.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/NameProtocol.java
eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DeletedProtocolTest.java
eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DescriptionProtocolTest.java
eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/NameProtocolTest.java
eventsourcing-core/src/main/java/com/eventsourcing/Model.java
eventsourcing-core/src/main/java/com/eventsourcing/Protocol.java
examples/order/.gitignore
examples/order/build.gradle
examples/order/src/main/java/com/eventsourcing/examples/order/NameProtocol.java
examples/order/src/main/java/com/eventsourcing/examples/order/Order.java
examples/order/src/main/java/com/eventsourcing/examples/order/PriceProtocol.java
examples/order/src/main/java/com/eventsourcing/examples/order/Product.java
examples/order/src/main/java/com/eventsourcing/examples/order/commands/AddProductToOrder.java
examples/order/src/test/java/com/eventsourcing/examples/order/OrderTest.java
examples/order/src/test/java/com/eventsourcing/examples/order/ProductTest.java

Solution: Rename #id() to #getId()

Problem: Model#id() naming is inconsistent with Model#getRepository()

---

eventsourcing-core/src/main/java/com/eventsourcing/events/CommandTerminatedExceptionally.java
eventsourcing-core/src/main/java/com/eventsourcing/events/JavaExceptionOccurred.java

Solution: add missing annotations

Problem: events in com.eventsourcing.events.* missing some `@Index` annotations

---

eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/DescriptionChanged.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/NameChanged.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DeletedProtocol.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DescriptionProtocol.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/NameProtocol.java
eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DeletedProtocolTest.java
eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DescriptionProtocolTest.java
eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/NameProtocolTest.java
eventsourcing-queries/src/main/java/com/eventsourcing/queries/ModelLoader.java

Solution: Provide these interfaces for NameProtocol, DescriptionProtocol
and DeletedProtocol

Problem: CEP protocols don't provide a composable query interface

---

eventsourcing-core/src/main/java/com/eventsourcing/index/EntityQueryFactory.java

Solution: define one in EntityQueryFactory

Problem: no matching query function for none(Class<? extends Entity>)

---

eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DeletedProtocol.java
eventsourcing-cep/src/test/java/com/eventsourcing/cep/protocols/DeletedProtocolTest.java

Solution: Add `DeletedProtocol.nonDeleted` composable model collection
query

Problem: difficult to query for "all not-deleted or undeleted" models

---

eventsourcing-core/build.gradle
eventsourcing-core/src/main/java/com/eventsourcing/index/AbstractAttribute.java
eventsourcing-core/src/test/java/com/eventsourcing/index/AbstractAttributeIndexTest.java
eventsourcing-h2/src/main/java/com/eventsourcing/h2/index/HashIndex.java
eventsourcing-h2/src/main/java/com/eventsourcing/h2/index/UniqueIndex.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/PostgreSQLAttributeIndex.java

Some internal APIs have changed
Solution: upgrade to 2.7.0

Problem: cqengine 2.6.0 has been superseded by 2.7.0

---

build.gradle
eventsourcing-postgresql/build.gradle

Solution: update them and add vplugin to track versions more
efficiently

Problem: some of the dependencies got superseded

---

.travis.yml
eventsourcing-postgresql/build.gradle
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLJournalTest.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLLockProviderTest.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLRepositoryTest.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLTest.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/index/PostgreSQLEqualityIndexTest.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/index/PostgreSQLNavigableIndexTest.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/index/PostgreSQLUniqueEqualityIndexTest.java

Soltion: use an embedded postgresql runner

Problem: running tests requires having a properly configured PostgreSQL

---

eventsourcing-repository/src/main/java/com/eventsourcing/repository/StandardRepository.java

It relies on CQEngine throwing an IllegalStateException with a specific message
Solution: use `#getIndexes` to find out if such an index is already present

Problem: StandardRepository's check for index pre-existence is hacky

---

eventsourcing-core/build.gradle

Problem: CQEngine 2.7.0 has been superseded

---

examples/foodsourcing/build.gradle
examples/foodsourcing/src/main/java/foodsourcing/Order.java
examples/foodsourcing/src/main/java/foodsourcing/OrderProcessManager.java
examples/foodsourcing/src/main/java/foodsourcing/commands/CapturePayment.java
examples/foodsourcing/src/main/java/foodsourcing/commands/ConfirmOrder.java
examples/foodsourcing/src/main/java/foodsourcing/commands/PlaceOrder.java
examples/foodsourcing/src/main/java/foodsourcing/commands/RequestRestaurantOrderConfirmation.java
examples/foodsourcing/src/main/java/foodsourcing/events/OrderConfirmed.java
examples/foodsourcing/src/main/java/foodsourcing/events/OrderPlaced.java
examples/foodsourcing/src/main/java/foodsourcing/events/PaymentCaptured.java
examples/foodsourcing/src/main/java/foodsourcing/events/RestaurantConfirmedOrder.java
examples/foodsourcing/src/main/resources/META-INF/kmodule.xml
examples/foodsourcing/src/main/resources/META-INF/maven/pom.properties
examples/foodsourcing/src/main/resources/foodsourcing/Order.drl
examples/foodsourcing/src/test/java/foodsourcing/OrderProcessManagerTest.java

Solution: provide a Drools-based example in foodsourcing

Problem: not clear how to implement a process manager

---

eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/Deleted.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/DescriptionChanged.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/NameChanged.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/events/Undeleted.java

RFC 3/CEP does not include protocol in the name of layouts
Solution: adjust the layout names to correspond to RFC 3/CEP

Problem: CEP events' layout names start with http://

---

eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLJournalTest.java

Solution: force PostgreSQL test to read back from the journal

Problem: PostgreSQL test doesn't test actual deserialization

---

eventsourcing-layout/src/main/java/com/eventsourcing/layout/TypeHandler.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/binary/BinarySerialization.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/binary/MapBinaryDeserializer.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/binary/MapBinarySerializer.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/comparable/ComparableSerialization.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/comparable/MapComparableSerializer.java
eventsourcing-layout/src/main/java/com/eventsourcing/layout/types/MapTypeHandler.java
eventsourcing-layout/src/test/java/com/eventsourcing/layout/SerializerTest.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLSerialization.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLJournalTest.java

It's a common and useful type
Solution: introduce Map

Problem: no associative array type

---

docs/getting_started/layout.md
eventsourcing-layout/src/main/java/com/eventsourcing/layout/TypeHandler.java

Problem: Map type can't be discovered by a new user

---

docs/getting_started/indexing.md

Problem: documentation still exposes old API for indices

---

eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DeletedProtocol.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DescriptionProtocol.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/NameProtocol.java
eventsourcing-core/build.gradle
eventsourcing-core/src/test/java/com/eventsourcing/index/EqualityIndexTest.java
examples/foodsourcing/src/main/java/foodsourcing/MenuItem.java
examples/foodsourcing/src/main/java/foodsourcing/Restaurant.java

Solution: update to cqengine 2.8.0

Problem: cqengine 2.7.1 is outdated

---

eventsourcing-hlc/src/main/java/com/eventsourcing/hlc/NTPServerTimeProvider.java
eventsourcing-hlc/src/test/java/com/eventsourcing/hlc/NTPServerTimeProviderTest.java

The failure to connect to a local NTP server is hard to detect (nothing is
happening, repository is not starting). Since NTP is a UDP protocol, we can't
reliably tell if there's an NTP server listening. The only way to tell if we're
not getting a response.
Solution: throw an exception after some reasonably high delay (2s)
Fixes #157

Problem: Absence of local NTP server silently locks es4j up

---

eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLSerialization.java

This is because PostgreSQL's name type is 64 bytes:
https://www.postgresql.org/docs/9.0/static/datatype-character.html
Solution: as a quick fix, before a more standadized and comprehensive
approach is implemented, shorten the name using a hash function,
similar to how it is done in index table names.

Problem: map type name in PostgreSQL can get too long and trimmed

---

build.gradle
eventsourcing-core/build.gradle
eventsourcing-h2/build.gradle
eventsourcing-hlc/build.gradle
eventsourcing-inmem/build.gradle
eventsourcing-layout/build.gradle

Problem: Guava 19.0 is outdated

---

eventsourcing-core/src/main/java/com/eventsourcing/Entity.java
eventsourcing-core/src/main/java/com/eventsourcing/StandardEntity.java

Solution: re-introduce the parameter

Problem: Entity interface drops type parameter

---

eventsourcing-layout/src/main/java/com/eventsourcing/layout/Layout.java

Solution: mention property type to make it clearer

Problem: Layout exception on property mismatched type is not clear

---

.travis.yml
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DeletedProtocol.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/DescriptionProtocol.java
eventsourcing-cep/src/main/java/com/eventsourcing/cep/protocols/NameProtocol.java
eventsourcing-core/build.gradle
eventsourcing-core/src/test/java/com/eventsourcing/index/EqualityIndexTest.java
examples/foodsourcing/build.gradle
examples/foodsourcing/src/main/java/foodsourcing/MenuItem.java
examples/foodsourcing/src/main/java/foodsourcing/Restaurant.java

Problem: cqengine 2.8.0 is oudated

---

eventsourcing-h2/build.gradle
eventsourcing-inmem/build.gradle
eventsourcing-postgresql/build.gradle
examples/foodsourcing/build.gradle

This dependency further complicates the dependency tree
Solution: remove this dependency

Problem: some storages depend on eventsourcing-repository

---

eventsourcing-kotlin/build.gradle

Problem: Kotlin 1.1-M03 has been outdated

---

eventsourcing-core/src/main/java/com/eventsourcing/index/CommandJournalPersistence.java
eventsourcing-core/src/main/java/com/eventsourcing/index/EventJournalPersistence.java

This makes implementing scanning queries extremely expensive
Solution: make it eager

Problem: iterating over a collection is still non-eager

---

eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLTest.java

For each group of tests, a new instance is extracted and launched.
Solution: share one instance but create isolated databases for
each group.

Problem: pgsql tests take too long

---

eventsourcing-core/src/main/java/com/eventsourcing/Journal.java
eventsourcing-hlc/src/main/java/com/eventsourcing/hlc/HybridTimestamp.java
eventsourcing-inmem/src/main/java/com/eventsourcing/inmem/MemoryJournal.java
eventsourcing-inmem/src/test/java/com/eventsourcing/inmem/MemoryJournalRepositoryTest.java
eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/PostgreSQLJournal.java
eventsourcing-postgresql/src/test/java/com/eventsourcing/postgresql/PostgreSQLRepositoryTest.java
eventsourcing-repository/src/main/java/com/eventsourcing/repository/CommandConsumerImpl.java
eventsourcing-repository/src/test/java/com/eventsourcing/repository/RepositoryTest.java

Solution: keep it in the journal

Problem: Repistory loses its exact last timestamp upon restart

---

eventsourcing-core/src/main/java/com/eventsourcing/queries/ComparingQuery.java
eventsourcing-core/src/main/java/com/eventsourcing/queries/Max.java
eventsourcing-core/src/main/java/com/eventsourcing/queries/Min.java

This seriously impacts overall readability and makes further improvements
or extensions much more difficult.
Solution: abstract that code away into ComparingQuery

Problem: Min & Max queries share a lot of code with little difference
